import type { CommitConstraints } from './settings.js';

/**
 * A file that has changed in the working tree.
 */
export interface ChangedFile {
  filePath: string;
  status: 'added' | 'modified' | 'deleted' | 'renamed' | 'untracked';
  staged: boolean;
}

/**
 * A proposed commit — generated by the auto-commit tool, presented for user approval.
 */
export interface CommitProposal {
  /** Generated commit message */
  message: string;
  /** Files to be included */
  files: ChangedFile[];
  /** Constraint validation result */
  constraintValidation: ConstraintValidation;
}

/**
 * Result of validating a commit message against CommitConstraints.
 */
export interface ConstraintValidation {
  /** True if all constraints pass */
  valid: boolean;
  /** Individual violations (empty if valid) */
  violations: ConstraintViolation[];
}

/**
 * A single constraint violation.
 */
export interface ConstraintViolation {
  /** Which constraint was violated */
  constraint: keyof CommitConstraints;
  /** Human-readable explanation */
  message: string;
  /** What we got */
  actual: string | number;
  /** What was expected */
  expected: string | number;
}

/**
 * Result of checking a pre-commit hook.
 */
export interface HookCheckResult {
  /** Hook name (e.g. 'pre-commit', 'commit-msg') */
  hookName: string;
  /** Whether the hook file exists */
  exists: boolean;
  /** Whether dry-run passed (undefined if not run) */
  dryRunPassed?: boolean;
  /** Hook output (stdout + stderr) */
  output?: string;
}

/**
 * TLDR summary of recent changes.
 */
export interface TldrSummary {
  /** What was summarized — file path, directory, or 'project' */
  scope: string;
  /** Start of the summarized time range */
  since: Date;
  /** End of the summarized time range */
  until: Date;
  /** How many commits were analyzed */
  commitCount: number;
  /** The generated summary text */
  summary: string;
  /** Key changes, grouped logically */
  highlights: TldrHighlight[];
}

/**
 * A single highlight in a TLDR summary.
 */
export interface TldrHighlight {
  /** What changed, in plain language */
  description: string;
  /** Relevant file paths */
  files: string[];
  /** Commit hashes that contributed to this highlight */
  commits: string[];
}
